"""Risk and operational threshold defaults."""

PROMOTION_MAX_BUYING_POWER_SKIP_RATE = 0.20

LOCK_WAIT_WARNING_SEC = 10
LOCK_WAIT_TELEGRAM_ALERT_SEC = 30
LOCK_WAIT_SKIP_SEC = 60
STARTUP_RECON_WATCHDOG_SEC = 300
KEEPALIVE_LOCK_WAIT_SEC = 2
RISK_MONITOR_LOCK_WAIT_SEC = 10
