"""System-wide skip reason constants.

These constants are payload values for SIGNAL_SKIPPED ledger events. They are
kept import-safe so scheduler/readiness code does not need to import strategy
modules just to name a skip reason.
"""

SKIP_HALTED = "SKIP_HALTED"
SKIP_EXISTING_POSITION = "SKIP_EXISTING_POSITION"
SKIP_BLACKOUT_DATE = "SKIP_BLACKOUT_DATE"
SKIP_VIX_GATE = "SKIP_VIX_GATE"
SKIP_IV_RANK_BELOW_MIN = "SKIP_IV_RANK_BELOW_MIN"
SKIP_NEEDS_RECONCILIATION = "SKIP_NEEDS_RECONCILIATION"
SKIP_ORDERREF_MISSING = "SKIP_ORDERREF_MISSING"

SKIP_NLV_DEGRADED = "SKIP_NLV_DEGRADED"
SKIP_UNKNOWN_BROKER_EXPOSURE = "SKIP_UNKNOWN_BROKER_EXPOSURE"
SKIP_ACCOUNT_SNAPSHOT_STALE = "SKIP_ACCOUNT_SNAPSHOT_STALE"
SKIP_STATESTORE_UNREADABLE = "SKIP_STATESTORE_UNREADABLE"
SKIP_IV_BASELINE_MISSING = "SKIP_IV_BASELINE_MISSING"

SKIP_LOCK_STARVATION = "SKIP_LOCK_STARVATION"
SKIP_ALREADY_SIGNALED_TODAY = "SKIP_ALREADY_SIGNALED_TODAY"
SKIP_ACTIVE_ORDER_INTENT = "SKIP_ACTIVE_ORDER_INTENT"
